server:
  port: 8082 # Cổng riêng cho Asset

spring:
  application:
    name: asset-service
  datasource:
    url: jdbc:mysql://localhost:3308/db_asset # Port 3308 như trong Docker
    username: root
    password: 123456 # Sửa lại cho khớp với Docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/